server:
  port: 8888
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rm
    password: rmp
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true
      enabled: true
    stream:
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
        springCloudBusInput:
          destination: springCloudBus
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka